Modify vimrc & Add scripts

diff --git a/script/ptime b/script/ptime
--- a/script/ptime
+++ b/script/ptime
@@ -3,8 +3,8 @@
 TIME_CMD=$(which time 2>/dev/null)
 
 if [ -z "$TIME_CMD" ]; then
-  echo "Error: 'time' command not found."
-  exit 1
+    echo "Error: 'time' command not found."
+    exit 1
 fi
 
 "$TIME_CMD" -p "$@"
