Add plugin andymass/vim-matchup

diff --git a/script/ptime b/script/ptime
--- a/script/ptime
+++ b/script/ptime
@@ -1,2 +1,11 @@
 #!/bin/bash
-/usr/bin/time -p "$@"
+
+TIME_CMD=$(which time 2>/dev/null)
+
+if [ -z "$TIME_CMD" ]; then
+  echo "Error: 'time' command not found."
+  exit 1
+fi
+
+"$TIME_CMD" -p "$@"
+
